/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Yan Kaic
 */
public class WhilePanel extends javax.swing.JPanel {

  /**
   * Creates new form WhilePanel
   */
  public WhilePanel() {
    initComponents();
  }

  @Override
  public void paintComponent(Graphics g) {
    super.paintComponent(g);
    Graphics2D graphics = (Graphics2D) g.create();
    graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    graphics.setPaint(getBackground());
    graphics.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    letter1 = new entities.Letter();

    setBackground(new java.awt.Color(255, 255, 255));
    setOpaque(false);
    setLayout(new java.awt.BorderLayout());

    letter1.setText("letter1");
    add(letter1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private entities.Letter letter1;
  // End of variables declaration//GEN-END:variables
}
