/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Yan Kaic
 */
public class BackgroundPanel extends javax.swing.JPanel {

  /**
   * Creates new form NovoJPanel
   */
  public BackgroundPanel() {
    initComponents();
  }
  
  @Override
  public void paintComponent(Graphics g){
    super.paintComponent(g);
    ImageIcon img = new ImageIcon(getClass().getResource("/images/background.jpg"));
    g.drawImage(img.getImage(), getPreferredSize().width, getHeight(), null);
    g.drawLine(0, 0, getWidth(), getHeight());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();

    setLayout(new java.awt.BorderLayout());

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
    add(jLabel1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
