/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.components;

/**
 *
 * @author Yan
 */
public class VideoPane extends javax.swing.JPanel {

  /**
   * Creates new form VideoPane
   */
  public VideoPane() {
    initComponents();
//    videoPlayer1.setSourceMedia(getClass().getResource("/videos/d.mp4").toString());
    add(videoPlayer1);
    videoPlayer1.getPlayer().play();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    videoPlayer1 = new view.components.VideoPlayer();

    javax.swing.GroupLayout videoPlayer1Layout = new javax.swing.GroupLayout(videoPlayer1.getContentPane());
    videoPlayer1.getContentPane().setLayout(videoPlayer1Layout);
    videoPlayer1Layout.setHorizontalGroup(
      videoPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    videoPlayer1Layout.setVerticalGroup(
      videoPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private view.components.VideoPlayer videoPlayer1;
  // End of variables declaration//GEN-END:variables
}
