/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.components;

/**
 *
 * @author Yan
 */
public class VideoPane extends javax.swing.JPanel {

  /**
   * Creates new form VideoPane
   */
  public VideoPane() {
    initComponents();
  }

  /**
   * método que seta o caminho do video que será reproduzido na animação
   * @param source String : caminho absoluto do video
   */
  public void setSourceMedia(String source){
      videoPlayer.setSourceMedia(source);
  }//fim setSourceMedia
  
  /**
   * Método que reproduz um video
   */
  public void play(){
      
  }//fim play
  
  /**
   * Método que encerra a reprodução de um video
   */
  public void close(){      
      
  }//fim close
  
  /**
   * Método que pausa a reprodução de um video
   */
  public void pause(){
  }//fim pause
  
  /**
   * Método que habilita ou desabilita o audio de um video
   */
  public void mute(){
      
  }//fim mute
  
  /**
   * Método que reinicializa a execução de uma video
   */
  public void restart(){
      
  }//fim restart
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        videoPlayer = new view.components.VideoPlayer();

        javax.swing.GroupLayout videoPlayerLayout = new javax.swing.GroupLayout(videoPlayer.getContentPane());
        videoPlayer.getContentPane().setLayout(videoPlayerLayout);
        videoPlayerLayout.setHorizontalGroup(
            videoPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        videoPlayerLayout.setVerticalGroup(
            videoPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.components.VideoPlayer videoPlayer;
    // End of variables declaration//GEN-END:variables
}
